{
  "text-color": "#d4d4d4",
  "background-color": "#1e1e1e",
  "line-number-color": "#858585",
  "line-number-background-color": "#1e1e1e",
  "text-styles": {
    "Alert": {
      "text-color": "#f44747",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Annotation": {
      "text-color": "#6a9955",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Attribute": {
      "text-color": "#9cdcfe",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#b5cea8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#dcdcaa",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#ce9178",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#6a9955",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#6a9955",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Constant": {
      "text-color": "#569cd6",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#c586c0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#4ec9b0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#b5cea8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Documentation": {
      "text-color": "#6a9955",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Error": {
      "text-color": "#f44747",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": true
    },
    "Extension": {
      "text-color": "#dcdcaa",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#b5cea8",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#dcdcaa",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#c586c0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#9cdcfe",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Keyword": {
      "text-color": "#569cd6",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Normal": {
      "text-color": "#d4d4d4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#d4d4d4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Other": {
      "text-color": "#d4d4d4",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#c586c0",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "RegionMarker": {
      "text-color": "#569cd6",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#d7ba7d",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#ce9178",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#ce9178",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#9cdcfe",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#ce9178",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#cca700",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    }
  }
}